kind: ConfigMap
apiVersion: v1
metadata:
  name: rocketmq-config
  namespace: default
data:
  broker.properties: |-
    storePathRootDir=/var/rocketmq/store
    storePathCommitLog=/var/rocketmq/store/commitlog